### ISSUE TITLE
support for data files

### ISSUE THREAD

**Issue by OwenBrotherwood** [Microsoft/pxt-filesystem#1]
The possiblity of data files that can be used by a program
Probably something that should be given thought to as to how to create a general solution.
use case should be added to this enhancement issue.
`
This is copied from slack: Jonny suggested to be able to add data files in the project (e.g. Text file) and we would automatically pre-populate the filesystem with those files when flashing the device.`

**Comment by pelikhan** [comment]
Please file this feature request in PXT.
