### ISSUE TITLE
File Download

### ISSUE THREAD

**Issue by damianburrin** [Microsoft/pxt-filesystem#10]
Is there currently no way to access and download the files saved to the microbit?  Dumping to serial is a problem as this tends to be blocked in UK schools :-(

The MicroPython version of file store has a utility call MicroFS that allows you to put and get the files.  So I can write my data as a csv file to the flash and then use the tool to "download" the file.

**Comment by fd0cwp** [comment]
I would like to have this option, too.

**Comment by pelikhan** [comment]
Waiting on DAPLink to support MSC and expose files through file explorer.
